- job:
    name: openstack-tox-py311-with-neutron
    parent: openstack-tox-py311
    # TODO(ykarel) Can switch to voting in next cycle(E)
    # if job found to be stable
    voting: false
    timeout: 3600
    vars:
      zuul_work_dir: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/neutron'].src_dir }}"
    required-projects:
      - openstack/neutron
      - openstack/neutron-lib

- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-python3-jobs
      - lib-forward-testing-python3
      - release-notes-jobs-python3
      - neutron-tempest-plugin-jobs-2024-2
    check:
      jobs:
        - openstack-tox-py311-with-neutron
        - neutron-functional-with-uwsgi:
            required-projects:
              - openstack/neutron-lib
        # This job comes from lib-forward-testing-python3 template,
        # but it is limited to 2h there and we want to set
        # for it 3h timeout
        - tempest-full-py3:
            timeout: 10800
    gate:
      jobs:
        - neutron-functional-with-uwsgi
        # This job comes from lib-forward-testing-python3 template,
        # but it is limited to 2h there and we want to set
        # for it 3h timeout
        - tempest-full-py3:
            timeout: 10800
